<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Autorisatie</name>
   <tag></tag>
   <elementGuidId>01fb34c0-07b7-4ace-a144-9e40ceb16b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;priemmenu&quot;]/div/ul/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;priemmenu&quot;]/div/ul/li[3]/span</value>
   </webElementProperties>
</WebElementEntity>
