<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HB</name>
   <tag></tag>
   <elementGuidId>5f937858-8c0d-43e4-9cd5-83901e402885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='priemmenu']/div/ul/li[1]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='priemmenu']/div/ul/li[1]/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
