<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame8</name>
   <tag></tag>
   <elementGuidId>40f6c199-307f-4ecd-8011-03b90c2b8709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifrm108</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ifrm108&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
