<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Onderhoud</name>
   <tag></tag>
   <elementGuidId>9e813121-7b5f-46db-9b2c-4c089af6f926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;priemmenu&quot;]/div/ul/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;priemmenu&quot;]/div/ul/li[2]/span</value>
   </webElementProperties>
</WebElementEntity>
