<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icici</name>
   <tag></tag>
   <elementGuidId>72064c7f-a4d9-4e70-9652-d1efe7283806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-mode > div:nth-child(1) > div.col-xs-20 > div:nth-child(1) > label > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1539614166114</value>
   </webElementProperties>
</WebElementEntity>
