<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>username</description>
   <name>userid</name>
   <tag></tag>
   <elementGuidId>8779cda7-2ba5-47be-b1a3-027f851bd9b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='nx_usr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='nx_usr']</value>
   </webElementProperties>
</WebElementEntity>
