<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logout</name>
   <tag></tag>
   <elementGuidId>e0cb6b2f-3bd6-4663-8658-833900f09e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sdHeader > div.headerBar.reset-padding > div.topBar.top-bar-homepage.top-freeze-reference-point > div > div.col-xs-5.reset-padding.header-right.rfloat > div.myAccountTab.accountHeaderClass.col-xs-13.reset-padding > div > div > div.dropdownAccount > div > ul > li.accountInfoNonLoggedIn.logoutNew > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1539613234843</value>
   </webElementProperties>
</WebElementEntity>
