<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ifrsearch</description>
   <name>popupiframe</name>
   <tag></tag>
   <elementGuidId>fb2009b5-92cc-4a49-a120-ed2adf4799d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifrsearch</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ifrsearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ifrsearch&quot;]</value>
   </webElementProperties>
</WebElementEntity>
