<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ifrmviewdoc</description>
   <name>rightiframe</name>
   <tag></tag>
   <elementGuidId>3ff3b96b-b07b-4924-8e4b-313bcccc10f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ifrmviewdoc&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifrmviewdoc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
