<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame8</name>
   <tag></tag>
   <elementGuidId>82d259cd-427a-4e91-bff3-90113621eaea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifrm108</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ifrm108&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
