<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>day selection</name>
   <tag></tag>
   <elementGuidId>ca00b982-7e0b-4b9b-838d-435d943e3a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PRKRRGDT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;PRKRRGDT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1540373364597</value>
   </webElementProperties>
</WebElementEntity>
